# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZDs8f--qFbzI5zAh2bei3MClVFSHT-4
"""

def draw_pyramid(rows):
    for i in range(1, rows + 1):
        spaces = ' ' * (rows - i)
        stars = '*' * (2 * i - 1)
        print(spaces + stars)

# Set the number of rows for the pyramid
num_rows = 5

# Call the function to draw the pyramid
draw_pyramid(num_rows)